# wandb
wandb_project: lbm-fill-lighting-refine
backbone_signature: stable-diffusion-v1-5/stable-diffusion-v1-5
unet_input_channels: 6
unet_output_channels: 3
block_out_channels: [64, 128, 256, 256]
layers_per_block: 2
timestep_sampling: custom_timesteps
selected_timesteps: [250, 500, 750, 1000]
prob: [0.25, 0.25, 0.25, 0.25]
#latent_loss_type: l2
#latent_loss_weight: 1.0
pixel_loss_type: lpips
pixel_loss_weight: 1.0
bridge_noise_sigma: 0.005
conditioning_images_keys: [rgb]
conditioning_masks_keys: []
source_key: source
target_key: target

# DATA ROOTS
train_data_root: /mnt/data1/ssy/render_people/fill-light-dataset/train
validation_data_root: /mnt/data1/ssy/render_people/fill-light-dataset/val
image_size: 1024
num_workers: 4
train_random_flip: true

batch_size: 1
learning_rate: 1e-4
optimizer: AdamW
num_steps: [1, 4]
log_interval: 500
resume_from_checkpoint: true
max_epochs: 10
save_interval: 10000
resume_ckpt_path: /mnt/data1/ssy/render_people/LBM/examples/training/checkpoints/fill_lighting_refine/epoch=0-step=10000.ckpt
save_ckpt_path: ./checkpoints
