train_config: examples/training/config/fill_lighting.yaml
checkpoint_path: ./checkpoints/last.ckpt
source_image: /path/to/albedo
rgb_image: /path/to/rgb
shading_image: null
light_params: /path/to/light_params
depth_image: /path/to/depth
light_scale: null
output_path: ./outputs/fill_lighting
num_inference_steps: 4
image_size: 512
device: cuda
torch_dtype: bfloat16
