train_config: examples/training/config/fill_lighting_refine.yaml
checkpoint_path: path/to/checkpoint.ckpt
output_path: ./outputs
image_size: 1024
num_inference_steps: 1
unet_input_channels: 6
unet_output_channels: 3
block_out_channels: [64, 128, 256, 256]
layers_per_block: 2
conditioning_images_keys: [rgb]
conditioning_masks_keys: []
